# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindows(object):
    def setupUi(self, MainWindows):
        MainWindows.setObjectName("MainWindows")
        MainWindows.resize(790, 417)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindows.sizePolicy().hasHeightForWidth())
        MainWindows.setSizePolicy(sizePolicy)
        MainWindows.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindows)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 771, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_tgs = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget_tgs.setFont(font)
        self.tableWidget_tgs.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_tgs.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_tgs.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_tgs.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_tgs.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_tgs.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_tgs.setObjectName("tableWidget_tgs")
        self.tableWidget_tgs.setColumnCount(3)
        self.tableWidget_tgs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tgs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tgs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tgs.setHorizontalHeaderItem(2, item)
        self.tableWidget_tgs.verticalHeader().setVisible(False)
        self.tableWidget_tgs.verticalHeader().setHighlightSections(False)
        self.verticalLayout.addWidget(self.tableWidget_tgs)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_alwaysontop = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_alwaysontop.setChecked(True)
        self.checkBox_alwaysontop.setObjectName("checkBox_alwaysontop")
        self.verticalLayout_2.addWidget(self.checkBox_alwaysontop)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_version = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_version.setObjectName("label_version")
        self.verticalLayout_2.addWidget(self.label_version)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.pushButton_github = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_github.sizePolicy().hasHeightForWidth())
        self.pushButton_github.setSizePolicy(sizePolicy)
        self.pushButton_github.setObjectName("pushButton_github")
        self.horizontalLayout.addWidget(self.pushButton_github)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindows.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindows)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 21))
        self.menubar.setObjectName("menubar")
        MainWindows.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindows)
        self.statusbar.setObjectName("statusbar")
        MainWindows.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindows)
        QtCore.QMetaObject.connectSlotsByName(MainWindows)

    def retranslateUi(self, MainWindows):
        _translate = QtCore.QCoreApplication.translate
        MainWindows.setWindowTitle(_translate("MainWindows", "DMR Korean Talkgroup Monitor by VK2CYO"))
        item = self.tableWidget_tgs.horizontalHeaderItem(0)
        item.setText(_translate("MainWindows", "TG"))
        item = self.tableWidget_tgs.horizontalHeaderItem(1)
        item.setText(_translate("MainWindows", "Active"))
        item = self.tableWidget_tgs.horizontalHeaderItem(2)
        item.setText(_translate("MainWindows", "Inactive"))
        self.checkBox_alwaysontop.setText(_translate("MainWindows", "항상 위에"))
        self.label.setText(_translate("MainWindows", "Developed by Chanyeol Yoo (VK2CYO)"))
        self.label_version.setText(_translate("MainWindows", "VERSION"))
        self.pushButton_github.setText(_translate("MainWindows", "GitHub"))
